# application.properties

spring.application.name=smartparking
server.port=8080

# DB config
spring.datasource.url=jdbc:postgresql://db.ojpufyapslzmygitujzj.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=juanvan2006@

# Custom config
parking.price=5000.0
