# use port 18080 to avoid collision
server.port=18080
spring.application.name=sebtl

# Change port from 5432 to 6543
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.tacxjbgbdnmlxywfudfh
spring.datasource.password=x3CPBCefWF4YVVxR
spring.datasource.driver-class-name=org.postgresql.Driver

# Useful for Supabase
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none