spring.application.name=sebtl

spring.datasource.url=jdbc:postgresql://db.ysguceprtnfbopurislw.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=se-btl-2026
spring.datasource.driver-class-name=org.postgresql.Driver

# Useful for Supabase
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update